<?php
if ( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly

/**
 * Provide a admin area view for the plugin
 *
 * This file is used to markup the admin-facing aspects of the plugin.
 * The plugin does not install or modify these services but simply performs .
 * validation based on their existence in the HTML code.
 *
 * @link       https://osdeibi.dev
 * @since      1.0.0
 *
 * @package    ONALBSEO_Seo
 * @subpackage ONALBSEO_Seo/admin/partials
 */
?>

<div class="container pb-5 mb-5">
    <nav class="navbar mt-4 fixed-top bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand my-3" href="#">
            </a>
            <button id="downloadbtn" type="button" class="btn btn-sm btn-warning" onclick="getPDF()"><i
                        class="fa-regular fa-file-pdf"></i> <?php esc_html_e("Download report", "bucky-seo"); ?>
            </button>
        </div>
    </nav>
</div>
<div id="seo-report" class="container">

    <div class="container">
        <h1 class="display-5"><?php esc_html_e("Site validator", "bucky-seo"); ?></h1>
        <?php
        $generateapplied_text = __('Report executed on', 'bucky-seo');
        $generatedby_text = __('Generated by', 'bucky-seo');
        $seo_tool_name = esc_html("Bucky SEO Tools");
        ?>
        <small><b><?php echo esc_html($generateapplied_text); ?></b>: <?php echo esc_html(get_site_url()); ?> |
            <b><?php echo esc_html($generatedby_text); ?></b>: <?php echo esc_html($seo_tool_name); ?></small>
        <span class="placeholder col-12 bg-success"></span>
        <div class="card-group">
            <div class="card">
                <div class="container text-center">
                    <i class="fa-brands fa-google fa-5x"></i>
                </div>
                <div class="card-body">
                    <h5 class="card-title text-center"><?php esc_html_e("Integration with Google Search Console", "bucky-seo"); ?></h5>
                    <?php if (isset($results['meta_tags']['google-site-verification'])): ?>
                        <div class="text-center alert alert-success" role="alert">
                            <?php esc_html_e("Your site is integrated with Google Search Console", "bucky-seo"); ?>
                        </div>
                    <?php else: ?>
                        <div class="text-center alert alert-danger" role="alert">
                            <?php esc_html_e("Your website doesn't have Google Search Console integrated. Integrating it is easy and free, and it will provide you with valuable insights about how people find your website on search results, show you which pages are indexed, and allow you to submit your sitemap.xml file.", "bucky-seo"); ?>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
            <div class="card">
                <div class="container text-center">
                    <i class="fa-brands fa-windows fa-5x"></i>
                </div>
                <div class="card-body">
                    <h5 class="card-title text-center"><?php esc_html_e("Bing Webmaster Tools verification", "bucky-seo"); ?></h5>
                    <?php if (isset($results['meta_tags']['msvalidate.01'])): ?>
                        <div class="text-center alert alert-success" role="alert">
                            <?php esc_html_e("Your site have integrated Bing webmaster Tools", "bucky-seo"); ?>
                        </div>
                    <?php else: ?>
                        <div class="text-center alert alert-warning" role="alert">
                            <?php esc_html_e("Bing Webmaster Tools is not enabled. Enabling it will allow Bing to crawl and index your website, potentially leading to faster discovery in search results.", "bucky-seo"); ?>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
            <div class="card">
                <div class="container text-center">
                    <i class="fa-brands fa-yandex fa-5x"></i>
                </div>
                <div class="card-body">
                    <h5 class="card-title text-center"><?php esc_html_e("Yandex Webmaster Tools verification", "bucky-seo"); ?></h5>
                    <?php if (isset($results['meta_tags']['yandex-verification'])): ?>
                        <div class="text-center alert alert-success" role="alert">
                            <?php esc_html_e("This site have the Yandex Webmaster tools integrated", "bucky-seo"); ?>
                        </div>
                    <?php else: ?>
                        <div class="text-center alert alert-warning" role="alert">
                            <?php esc_html_e("Yandex verification wasn't found. Verifying your site ownership with Yandex Webmaster Tools provides tools for crawling, indexing, and analyzing your website's pages, along with a technical SEO health report.", "bucky-seo"); ?>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>

    <div class="container breakhtml2pdf">
        <h1 class="display-5"><?php esc_html_e("Search engine visibility", "bucky-seo"); ?></h1>
        <small><b><?php echo esc_html($generateapplied_text); ?></b>: <?php echo esc_html(get_site_url()); ?> |
            <b><?php echo esc_html($generatedby_text); ?></b>: <?php echo esc_html($seo_tool_name); ?></small>
        <span class="placeholder col-12 bg-success"></span>
        <div class="card-group">
            <div class="card">
                <div class="container text-center">
                    <i class="fa-solid fa-robot fa-5x"></i>
                </div>
                <div class="card-body">
                    <h5 class="card-title text-center"><?php esc_html_e("Robots directive", "bucky-seo"); ?></h5>
                    <?php if (isset($results['meta_tags']['robots'])): ?>
                        <?php if ($results['meta_tags']['robots'] === "noindex, nofollow"): ?>
                            <div class="text-center alert alert-danger" role="alert">
                                <?php esc_html_e("Your site is not visible to search engines. This means it won't appear in search results.", "bucky-seo"); ?>
                            </div>
                            <div class="text-center"><a><b><?php esc_html_e("Actual configuration", "bucky-seo"); ?></b>: <?php echo esc_html($results['meta_tags']['robots']); ?>
                                </a></div>
                        <?php else: ?>
                            <div class="text-center alert alert-success" role="alert">
                                <?php esc_html_e("Your site is visible to search engines and will be included in search results.", "bucky-seo"); ?>
                            </div>
                            <div class="text-center"><a><b><?php esc_html_e("Actual configuration", "bucky-seo"); ?></b>: <?php echo esc_html($results['meta_tags']['robots']); ?>
                                </a></div>
                        <?php endif; ?>
                    <?php else: ?>
                        <div class="text-center alert alert-danger" role="alert">
                            <?php esc_html_e("Not found", "bucky-seo"); ?>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>

    <div class="container breakhtml2pdf">
        <h1 class="display-5">Meta tags</h1>
        <small><b><?php echo esc_html($generateapplied_text); ?></b>: <?php echo esc_html(get_site_url()); ?> |
            <b><?php echo esc_html($generatedby_text); ?></b>: <?php echo esc_html($seo_tool_name); ?></small>
        <span class="placeholder col-12 bg-success"></span>
        <div class="card-group">
            <div class="card">
                <div class="container text-center">
                    <i class="fa-solid fa-text-height fa-5x"></i>
                </div>
                <div class="card-body">
                    <h5 class="card-title text-center"><?php esc_html_e("Seo title", "bucky-seo"); ?></h5>
                    <?php if (isset($results['meta_tags']['title'])): ?>
                        <?php if (strlen($results['meta_tags']['title']) > 60): ?>
                            <div class="text-center alert alert-danger" role="alert">
                                <?php esc_html_e("The title is more than 60 characters and may not be fully visible in search results.", "bucky-seo"); ?>
                            </div>
                            <b><?php esc_html_e("Title", "bucky-seo"); ?></b>: <?php echo esc_html($results['meta_tags']['title']); ?>
                        <?php else: ?>
                            <div class="text-center alert alert-success" role="alert">
                                <?php esc_html_e("The page's title has a good character count, ensuring it's both visible in search results and user-friendly.", "bucky-seo"); ?>
                            </div>
                            <b><?php esc_html_e("Title", "bucky-seo"); ?></b>: <?php echo esc_html($results['meta_tags']['title']); ?>
                        <?php endif; ?>
                    <?php else: ?>
                        <div class="text-center alert alert-danger" role="alert">
                            <?php esc_html_e("The page doesn't have a title. This can hurt your SEO, as it won't be displayed in search results.", "bucky-seo"); ?>

                        </div>
                    <?php endif; ?>
                </div>
            </div>

            <div class="card">
                <div class="container text-center">
                    <i class="fa-solid fa-book-open fa-5x"></i>
                </div>
                <div class="card-body">
                    <h5 class="card-title text-center"><?php esc_html_e("SEO description", "bucky-seo"); ?></h5>
                    <?php if (isset($results['meta_tags']['description'])): ?>
                        <?php if (strlen($results['meta_tags']['description']) > 170): ?>
                            <div class="text-center alert alert-danger" role="alert">
                                <?php esc_html_e("Your description exceeds 170 characters, the recommended limit for optimal display in search results. Consider shortening it to improve readability.", "bucky-seo"); ?>
                            </div>
                            <b><?php esc_html_e("Description", "bucky-seo"); ?></b>: <?php echo esc_html($results['meta_tags']['description']); ?>
                        <?php else: ?>
                            <div class="text-center alert alert-success" role="alert">
                                <?php esc_html_e("Great job with the descriptions! They're concise and user-friendly for search results.", "bucky-seo"); ?>
                            </div>
                            <b><?php esc_html_e("Description", "bucky-seo"); ?></b>: <?php echo esc_html($results['meta_tags']['description']); ?>
                        <?php endif; ?>
                    <?php else: ?>
                        <div class="text-center alert alert-danger" role="alert">
                            <?php esc_html_e("There is no description for your page. This can hurt users' experience, and your site might not appear with the correct description if you don't provide one.", "bucky-seo"); ?>
                        </div>
                    <?php endif; ?>
                </div>
            </div>

        </div>

        <div class="card-group">
            <div class="card">
                <div class="container text-center">
                    <i class="fa-solid fa-key fa-5x"></i>
                </div>
                <div class="card-body">
                    <h5 class="card-title text-center"><?php esc_html_e("Keywords", "bucky-seo"); ?></h5>
                    <?php if (isset($results['meta_tags']['keywords'])): ?>
                        <?php $keywords = $results['meta_tags']['keywords'];
                        $word_count = str_word_count($keywords, 0, ','); ?>
                        <div class="text-center alert alert-success" role="alert">
                            <?php esc_html_e("Total Keywords", "bucky-seo"); ?>: <?php echo esc_html($word_count); ?>
                        </div>
                        <b><?php esc_html_e("Keywords", "bucky-seo"); ?></b>: <?php echo esc_html($keywords); ?>
                    <?php else: ?>
                        <div class="text-center alert alert-danger" role="alert">
                            <?php esc_html_e("Your page doesn't have keywords assigned. Including relevant keywords can help search engines understand your content and improve your website's ranking.", "bucky-seo"); ?>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>

    <div class="container breakhtml2pdf">
        <h1 class="display-5"><?php esc_html_e("Analytics", "bucky-seo"); ?></h1>
        <small><b><?php echo esc_html($generateapplied_text); ?></b>: <?php echo esc_html(get_site_url()); ?> |
            <b><?php echo esc_html($generatedby_text); ?></b>: <?php echo esc_html($seo_tool_name); ?></small>
        <span class="placeholder col-12 bg-success"></span>
        <div class="card-group">
            <div class="card">
                <div class="container text-center">
                    <i class="fa-solid fa-chart-simple fa-5x"></i>
                </div>
                <div class="card-body">
                    <h5 class="card-title text-center">Google Analytics 4</h5>
                    <?php $found_script = false;
                    $count_repeats = 0;
                    foreach ($results['script_tags'] as $src):
                        if (strpos($src, 'googletagmanager.com/gtag/js?id=') !== false):
                            $found_script = true;
                            $count_repeats++;
                        endif;
                    endforeach;
                    if ($found_script): if ($count_repeats >= 2): ?>
                        <div class="text-center alert alert-warning" role="alert">
                            <?php esc_html_e("Your site has duplicate Analytics scripts. Merging them or removing unused ones can improve performance and follow Google's recommendations.", "bucky-seo"); ?>
                        </div>
                    <?php else: ?>
                        <div class="text-center alert alert-success" role="alert">
                            <?php esc_html_e("Your site have the correct integration with GA4", "bucky-seo"); ?>
                        </div>
                    <?php endif; ?>
                    <?php else: ?>
                        <div class="text-center alert alert-danger" role="alert">
                            <?php esc_html_e("Integrating Google Analytics 4 unlocks valuable insights into user behavior on your website. Consider setting it up to understand how visitors interact with your site.", "bucky-seo"); ?>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>

    <div class="container breakhtml2pdf">
        <h1 class="display-5"><?php esc_html_e("Technical SEO", "bucky-seo"); ?></h1>
        <small><b><?php echo esc_html($generateapplied_text); ?></b>: <?php echo esc_html(get_site_url()); ?> |
            <b><?php echo esc_html($generatedby_text); ?></b>: <?php echo esc_html($seo_tool_name); ?></small>
        <span class="placeholder col-12 bg-success"></span>
        <div class="card-group">
            <div class="card">
                <div class="container text-center">
                    <i class="fa-solid fa-file-zipper fa-5x"></i>
                </div>
                <div class="card-body">
                    <h5 class="card-title text-center"><?php esc_html_e("Gzip compression", "bucky-seo"); ?></h5>
                    <?php if ($results['gzip_enabled']): ?>
                        <div class="text-center alert alert-success" role="alert">
                            <?php esc_html_e("The site have Gzip compression enabled", "bucky-seo"); ?>
                        </div>
                    <?php else: ?>
                        <div class="text-center alert alert-warning" role="alert">
                            <?php esc_html_e("Your website would benefit from Gzip compression. Enabling it reduces file sizes and improves loading speed.", "bucky-seo"); ?>
                        </div>
                    <?php endif; ?>
                    <p>
                        <?php esc_html_e("Gzip compression is a method of compression and decompression that reduces the size of each file, improving website load and performance.", "bucky-seo"); ?>
                    </p>
                </div>
            </div>

            <div class="card">
                <div class="container text-center">
                    <i class="fa-brands fa-cloudflare fa-5x"></i>
                </div>
                <div class="card-body">
                    <h5 class="card-title text-center">Cloudflare</h5>
                    <?php if ($results['is_cloudflare']): ?>
                        <div class="text-center alert alert-success" role="alert">
                            <?php esc_html_e("Your site have Cloudflare enabled", "bucky-seo"); ?>
                        </div>
                    <?php else: ?>
                        <div class="text-center alert alert-warning" role="alert">
                            <?php esc_html_e("Cloudflare not enabled.", "bucky-seo"); ?>
                        </div>
                    <?php endif; ?>
                    <p>
                        <?php esc_html_e("Cloudflare improves latency and performance. Utilizing the cache option can further accelerate your website's content delivery and potentially improve SEO.", "bucky-seo"); ?>
                    </p>
                </div>
            </div>

            <div class="card">
                <div class="container text-center">
                    <i class="fa-solid fa-code fa-5x"></i>
                </div>
                <div class="card-body">
                    <h5 class="card-title text-center">Iframe</h5>
                    <?php
                    $count_iframes = !empty($results['iframe_tags']) ? count($results['iframe_tags']) : 0;
                    ?>
                    <?php if ($count_iframes > 0): ?>
                        <div class="text-center alert alert-warning" role="alert">
                            <?php esc_html_e("Total Iframes", "bucky-seo"); ?>: <?php echo esc_html($count_iframes); ?>
                        </div>
                    <?php else: ?>
                        <div class="text-center alert alert-danger" role="alert">
                            <?php esc_html_e("Iframes not found on the page", "bucky-seo"); ?>
                        </div>
                    <?php endif; ?>
                    <p><?php esc_html_e("iFrames don't affect SEO as much as you might think, Google still advises that you only use them when absolutely necessary.", "bucky-seo"); ?></p>

                    <?php if ($count_iframes > 0): ?>
                        <ul class="list-group">
                            <?php foreach ($results['iframe_tags'] as $iframe): ?>
                                <li class="list-group-item list-group-item-warning"><?php echo esc_html($iframe); ?></li>

                            <?php endforeach; ?>
                        </ul>
                    <?php else: ?>

                    <?php endif; ?>

                </div>
            </div>

        </div>


        <div class="card-group">
            <div class="card">
                <div class="container text-center">
                    <i class="fa-solid fa-file-code fa-5x"></i>
                </div>
                <div class="card-body">
                    <h5 class="card-title text-center"><?php esc_html_e("Minified JS", "bucky-seo"); ?> </h5>
                    <?php
                    $count_js = 0;
                    $count_minified_js = 0;
                    $unminified_js = array();
                    foreach ($results['script_tags'] as $src):
                        if (strpos($src, '.js') !== false && strpos($src, '.min.js') === false) {
                            $count_js++;
                            $unminified_js[] = $src;
                        } elseif (strpos($src, '.min.js') !== false) {
                            $count_minified_js++;
                        }
                    endforeach;
                    ?>
                    <?php if ($count_js > 0 || $count_minified_js > 0): ?>
                        <?php if ($count_js == 0 && $count_minified_js > 0): ?>
                            <div class="text-center alert alert-success" role="alert">
                                <?php esc_html_e("Great! All your Javascript is minified", "bucky-seo"); ?> | MinJS:<span id="count-minjs"><?php echo esc_html($count_minified_js) ?></span>  JS:<span id="count_js"><?php echo esc_html($count_js) ?></span>
                            </div>
                        <?php else: ?>
                            <div class="text-center alert alert-warning" role="alert">
                                <?php esc_html_e("Minified Javascripts", "bucky-seo"); ?>
                                : <?php echo esc_html($count_minified_js); ?>
                                <br>
                                <?php esc_html_e("Unminified Javascript", "bucky-seo"); ?>: <span
                                        class="badge text-bg-danger rounded-pill"><?php echo esc_html($count_js); ?> </span>
                            </div>
                            <p>
                            </p>
                        <?php endif; ?>
                    <?php else: ?>
                        <div class="text-center alert alert-danger" role="alert">
                            <?php esc_html_e("Your website does not have any JavaScript files minified.", "bucky-seo"); ?>
                        </div>
                    <?php endif; ?>
                    <p><?php esc_html_e("Minifying your JavaScript can significantly reduce its size (up to 40-70%), improving website loading speed.", "bucky-seo"); ?></p>
                    <div>
                        <canvas id="js-minify"></canvas>
                    </div>
                </div>
            </div>
            <?php if ($count_js > 0): ?>

                <div class="card">
                    <div class="container text-center">
                        <i class="fa-solid fa-file-lines fa-5x"></i>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title text-center"><?php esc_html_e("JS files without minify", "bucky-seo"); ?></h5>


                        <table class="mt-5 table table-striped">
                            <thead class="table-dark">
                            <tr>
                                <th scope="col"><?php esc_html_e("File type", "bucky-seo"); ?></th>
                                <th scope="col"><?php esc_html_e("File", "bucky-seo"); ?></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach ($unminified_js as $js): ?>

                                <tr>
                                    <td>Javascript</td>
                                    <td><?php echo esc_html($js); ?></td>
                                </tr>
                            <?php endforeach; ?>

                            </tbody>
                        </table>


                    </div>
                </div>
            <?php else: ?>

            <?php endif; ?>

        </div>

        <div class="card-group">

            <div class="card">
                <div class="container text-center">
                    <i class="fa-solid fa-file-lines fa-5x"></i>
                </div>
                <div class="card-body">
                    <h5 class="card-title text-center"><?php esc_html_e("Minified CSS", "bucky-seo"); ?></h5>
                    <?php $count_css = 0;
                    $count_minified = 0;
                    $unminified_css = array();
                    foreach ($results['stylesheets'] as $href):
                        if (strpos($href, '.css') !== false && strpos($href, '.min.css') === false) {
                            $count_css++;
                            $unminified_css[] = $href;
                        } elseif (strpos($href, '.min.css') !== false) {
                            $count_minified++;
                        }
                    endforeach;
                    ?>
                    <?php if ($count_css > 0 || $count_minified > 0): ?>
                        <?php if ($count_css == 0 && $count_minified > 0): ?>
                            <div class="text-center alert alert-success" role="alert">
                                <?php esc_html_e("Great! all your CSS are minified", "bucky-seo"); ?> | MinCss:<span id="count-mincss"><?php echo esc_html($count_minified) ?></span> CSS:<span id="count-css"><?php echo esc_html($count_css) ?></span>
                            </div>
                        <?php else: ?>
                            <div class="text-center alert alert-warning" role="alert">
                                <?php esc_html_e("Minified CSS files", "bucky-seo"); ?>
                                : <?php echo esc_html($count_minified); ?>
                                <br>
                                <?php esc_html_e("CSS files without minify", "bucky-seo"); ?>: <span
                                        class="badge text-bg-danger rounded-pill"><?php echo esc_html($count_css); ?></span>
                            </div>

                        <?php endif; ?>
                    <?php else: ?>
                        <div class="text-center alert alert-danger" role="alert">
                            <?php esc_html_e("Your website does not have any CSS files minified.", "bucky-seo"); ?>
                        </div>
                    <?php endif; ?>
                    <p>
                        <?php esc_html_e("Minifying your CSS can significantly reduce its size (up to 40-70%), improving website loading speed.", "bucky-seo"); ?>
                    </p>
                    <div>
                        <canvas id="css-minify"></canvas>
                    </div>

                </div>
            </div>
            <?php if ($count_css > 0): ?>

                <div class="card">
                    <div class="container text-center">
                        <i class="fa-solid fa-file-code fa-5x"></i>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title text-center"><?php esc_html_e("CSS files without minification", "bucky-seo"); ?></h5>
                        <table class="mt-5 table table-striped">
                            <thead class="table-dark">
                            <tr>
                                <th scope="col"><?php esc_html_e("File type", "bucky-seo"); ?></th>
                                <th scope="col"><?php esc_html_e("File", "bucky-seo"); ?></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach ($unminified_css as $css): ?>

                                <tr>
                                    <td><?php esc_html_e("Stylesheet", "bucky-seo"); ?></td>
                                    <td><?php echo esc_html($css); ?></td>
                                </tr>
                            <?php endforeach; ?>

                            </tbody>
                        </table>

                    </div>
                </div>
            <?php else: ?>

            <?php endif; ?>

        </div>

        <div class="card-group">
            <div class="card">
                <div class="container text-center">
                    <i class="fa-solid fa-images fa-5x"></i>
                </div>
                <div class="card-body">
                    <h5 class="card-title text-center"><?php esc_html_e("Next-Gen images", "bucky-seo"); ?>: WebP</h5>
                    <p>
                        <?php esc_html_e("WebP image format excels at compression. This translates to smaller file sizes without sacrificing image quality, ultimately improving website loading speed.", "bucky-seo"); ?>
                    </p>
                    <?php
                    $webp_count = 0;
                    $jpg_count = 0;
                    $jpeg_count = 0;
                    $png_count = 0;

                    // Verifica si $results['img_tags'] no es nulo y es un array
                    if (!is_null($results['img_tags']) && is_array($results['img_tags'])) {
                        foreach ($results['img_tags'] as $src) {
                            if (strpos($src, '.webp') !== false) {
                                $webp_count++;
                            } elseif (strpos($src, '.jpg') !== false) {
                                $jpg_count++;
                            } elseif (strpos($src, '.jpeg') !== false) {
                                $jpeg_count++;
                            } elseif (strpos($src, '.png') !== false) {
                                $png_count++;
                            }
                        }
                    }
                    ?>
                    <?php if ($webp_count > 0): ?>
                        <?php if ($jpg_count > 0 || $png_count > 0 || $jpeg_count > 0): ?>
                            <div class="text-center alert alert-warning" role="alert">
                                <?php esc_html_e("WebP images are present on the page, but other formats like JPG and PNG are also used. Consider converting these images to WebP for better compression.", "bucky-seo"); ?>
                            </div>
                            <?php if ($jpg_count > 0 || $png_count > 0 || $jpeg_count > 0): ?>
                                <canvas id="webp-chart"></canvas>
                            <?php endif; ?><canvas id="webp-chart"></canvas>
                        <?php else: ?>
                            <div class="text-center alert alert-success" role="alert">
                                <?php esc_html_e("Page contains WebP images.", "bucky-seo"); ?> | JPG:<span id="count-jpg"><?php echo esc_html($jpg_count) ?></span> JPEG:<span id="count-jpeg"><?php echo esc_html($jpeg_count) ?></span> WebP:<span id="count-webp"><?php echo esc_html($webp_count) ?></span> PNG:<span id="count-png"><?php echo esc_html($png_count) ?></span>
                            </div>
                        <?php endif; ?>
                    <?php else: ?>
                        <div class="text-center alert alert-danger" role="alert">
                            <?php esc_html_e("WebP images are not found on the page", "bucky-seo"); ?>
                        </div>
                    <?php endif; ?>
                    <canvas id="webp-chart"></canvas>
                </div>

            </div>

            <?php if ($jpg_count > 0 || $png_count > 0 || $jpeg_count > 0): ?>
                <div class="card">
                    <div class="container text-center">
                        <i class="fa-solid fa-images fa-5x"></i>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title text-center"><?php esc_html_e("Images that can be converted to WebP", "bucky-seo"); ?></h5>

                        <!-- tabla imaggenes jpg -->
                        <?php if ($jpg_count > 0): ?>
                            <table class="mt-5 table table-striped">
                                <thead class="table-dark">
                                <tr>
                                    <th scope="col">JPG</th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php
                                // Filtrar solo las imágenes en formato png
                                $jpg_images = array_filter($results['img_tags'], function ($img) {
                                    return strpos($img, '.jpg') !== false;
                                });

                                // Iterar sobre las imágenes png
                                foreach ($jpg_images as $jpg): ?>
                                    <tr>
                                        <td><?php echo esc_url($jpg); ?></td>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                            </table>
                        <?php else: ?>

                        <?php endif; ?>

                        <!-- tabla imagenes jpeg -->
                        <?php if ($jpeg_count > 0): ?>
                            <table class="mt-5 table table-striped">
                                <thead class="table-dark">
                                <tr>
                                    <th scope="col">JPEG</th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php
                                // Filtrar solo las imágenes en formato png
                                $jpeg_images = array_filter($results['img_tags'], function ($img) {
                                    return strpos($img, '.jpeg') !== false;
                                });

                                // Iterar sobre las imágenes png
                                foreach ($jpeg_images as $jpeg): ?>
                                    <tr>
                                        <td><?php echo esc_url($jpeg); ?></td>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                            </table>
                        <?php else: ?>

                        <?php endif; ?>

                        <!-- Tabla para png -->
                        <?php if ($png_count > 0): ?>
                            <table class="mt-5 table table-striped">
                                <thead class="table-dark">
                                <tr>
                                    <th scope="col">PNG</th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php
                                // Filtrar solo las imágenes en formato png
                                $png_images = array_filter($results['img_tags'], function ($img) {
                                    return strpos($img, '.png') !== false;
                                });

                                // Iterar sobre las imágenes png
                                foreach ($png_images as $png): ?>
                                    <tr>
                                        <td><?php echo esc_url($png); ?></td>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                            </table>
                        <?php else: ?>

                        <?php endif; ?>
                    </div>
                </div>
            <?php endif; ?>

        </div>

        <div class="container breakhtml2pdf">
            <h1 class="display-5"><?php esc_html_e("Content Analysis", "bucky-seo"); ?></h1>
            <small><b><?php echo esc_html($generateapplied_text); ?></b>: <?php echo esc_html(get_site_url()); ?> |
                <b><?php echo esc_html($generatedby_text); ?></b>: <?php echo esc_html($seo_tool_name); ?></small>
            <span class="placeholder col-12 bg-success"></span>
            <div class="card-group">
                <div class="card">
                    <div class="container text-center">
                        <i class="fa-solid fa-square-poll-horizontal fa-5x"></i>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title text-center"><?php esc_html_e("Structured data", "bucky-seo"); ?></h5>
                        <p><?php esc_html_e("Structured data is a way to provide search engines with additional information about a page, which can enhance search results with richer snippets.", "bucky-seo"); ?>
                        </p>
                        <?php
                        $count_strucutred = !empty($results['structured_data']) ? count($results['structured_data']) : 0;
                        ?>
                        <?php if ($count_strucutred > 0): ?>
                            <div class="alert alert-success" role="alert">
                                <?php esc_html_e("Strucutred data on your page", "bucky-seo"); ?>
                                : <?php echo esc_html($count_strucutred); ?>
                            </div>
                        <?php else: ?>
                            <div class="alert alert-danger" role="alert">
                                <?php esc_html_e("No structured data found.", "bucky-seo"); ?>
                            </div>
                        <?php endif; ?>

                        <?php if ($count_strucutred > 0): ?>
                            <ul class="list-group">
                                <?php foreach ($results['structured_data'] as $typeofstructured): ?>
                                    <li class="list-group-item list-group-item-primary"><?php echo esc_html($typeofstructured); ?></li>
                                <?php endforeach; ?>
                            </ul>
                        <?php else: ?>
                            <p><?php esc_html_e("Strucutred data not found", "bucky-seo"); ?></p>
                        <?php endif; ?>
                    </div>
                </div>
                <div class="card">
                    <div class="container text-center">
                        <i class="fa-solid fa-earth-americas fa-5x"></i>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title text-center">Hreflang</h5>
                        <p>
                            <?php esc_html_e("Hreflang is used for websites that offer content in multiple languages and regions. It helps search engines understand which version of your website is most relevant for a particular user's search query.", "bucky-seo"); ?>
                        </p>
                        <?php
                        // Contar la cantidad de enlaces hreflang
                        $count_hreflang_links = !empty($results['alternate_links']) ? count($results['alternate_links']) : 0;
                        ?>
                        <?php if ($count_hreflang_links > 0): ?>
                            <div class="alert alert-success" role="alert">
                                <?php esc_html_e("Total Hrefland", "bucky-seo"); ?>
                                : <?php echo esc_html($count_hreflang_links); ?>
                            </div>
                        <?php else: ?>
                            <div class="alert alert-warning" role="alert">
                                <?php esc_html_e("Hreflang not found", "bucky-seo"); ?>
                            </div>
                        <?php endif; ?>

                        <?php if ($count_hreflang_links > 0): ?>
                            <table class="table table table-striped">
                                <thead class="table-dark">
                                <tr>
                                    <th scope="col"><?php esc_html_e("Language", "bucky-seo"); ?></th>
                                    <th scope="col">URL</th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php foreach ($results['alternate_links'] as $hreflang_link): ?>
                                    <tr>
                                        <th scope="row"><?php echo esc_html($hreflang_link['hreflang']); ?></th>
                                        <td><a href="<?php echo esc_url($hreflang_link['href']); ?>"
                                               target="_blank"><?php echo esc_html($hreflang_link['href']); ?></a></td>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                            </table>
                        <?php else: ?>
                        <?php endif; ?>
                    </div>
                </div>

            </div>

            <div class="card-group">
                <div class="card">
                    <div class="container text-center">
                        <i class="fa-solid fa-heading fa-5x"></i>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title text-center">Titulos H1</h5>
                        <p>
                            <?php esc_html_e("For best accessibility practices, it's recommended to use only one H1 tag per page to clearly define the main heading and improve screen reader navigation.", "bucky-seo"); ?>
                        </p>
                        <?php $count_h1 = !empty($results['h1_tags']) ? count($results['h1_tags']) : 0; ?>
                        <?php if ($count_h1 > 0): ?>
                            <div class="alert alert-warning" role="alert">
                                <?php esc_html_e("Total of H1 tags", "bucky-seo"); ?>
                                : <?php echo esc_html($count_h1); ?>
                            </div>

                        <?php endif; ?>

                        <?php if ($count_h1 > 0): ?>
                            <div class="list-group">
                                <?php foreach ($results['h1_tags'] as $h1): ?>
                                    <a class="list-group-item list-group-item-warning list-group-item-action"><b><?php esc_html_e("Title", "bucky-seo"); ?></b>: <?php echo esc_html($h1); ?>
                                    </a>
                                <?php endforeach; ?>
                            </div>
                        <?php else: ?>
                            <p><?php esc_html_e("H1 tags not found", "bucky-seo"); ?></p>
                        <?php endif; ?>
                    </div>
                </div>
                <div class="card">
                    <div class="container text-center">
                        <i class="fa-solid fa-copy fa-5x"></i>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title text-center">Canonical</h5>
                        <?php
                        // Contar la cantidad de enlaces canonical
                        $count_canonical_links = !empty($results['canonical_links']) ? count($results['canonical_links']) : 0;
                        ?>
                        <?php if ($count_canonical_links > 0): ?>
                            <div class="alert alert-success" role="alert">
                                <?php esc_html_e("Canonical tags", "bucky-seo"); ?>
                                : <?php echo esc_html($count_canonical_links); ?>
                            </div>

                        <?php else: ?>
                            <div class="alert alert-warning" role="alert">
                                <?php esc_html_e("Canonical tags not found", "bucky-seo"); ?>
                            </div>
                        <?php endif; ?>

                        <?php if ($count_canonical_links > 0): ?>
                            <table class="table table-striped">
                                <thead>
                                <tr>
                                    <th scope="col">URL</th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php foreach ($results['canonical_links'] as $canonical_link): ?>
                                    <tr>
                                        <td><a href="<?php echo esc_html($canonical_link); ?>"
                                               target="_blank"><?php echo esc_html($canonical_link); ?></a></td>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                            </table>
                        <?php else: ?>
                            <p><?php esc_html_e("Canonical tags not found", "bucky-seo"); ?></p>
                        <?php endif; ?>
                    </div>
                </div>

            </div>


        </div>

        <div class="container breakhtml2pdf">
            <h1 class="display-5">Mobile</h1>
            <small><b><?php echo esc_html($generateapplied_text); ?></b>: <?php echo esc_html(get_site_url()); ?> |
                <b><?php echo esc_html($generatedby_text); ?></b>: <?php echo esc_html($seo_tool_name); ?></small>
            <span class="placeholder col-12 bg-success"></span>
            <div class="card-group">
                <div class="card">
                    <div class="container text-center">
                        <i class="fa-solid fa-mobile-screen-button fa-5x"></i>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title text-center">Viewport</h5>
                        <p>
                            <?php esc_html_e("Viewport is an HTML5 meta tag that defines the viewport's dimensions, which is the user's visible area of the webpage on their device.", "bucky-seo"); ?>

                        </p>
                        <?php if (isset($results['meta_tags']['viewport'])): ?>
                            <div class="text-center alert alert-success" role="alert">
                                <?php esc_html_e("For optimal user experience across devices, consider configuring a viewport meta tag to define the visible area of your webpage.", "bucky-seo"); ?>
                            </div>
                            <div class="mb-4 row">
                                <label for="viewport" class="col-sm-12 col-form-label text-start">Viewport:</label>
                                <div class="col-sm-12">
                                    <input class="form-control" id="viewport" type="text"
                                           value="<?php echo esc_html(($results['meta_tags']['viewport'])); ?>"
                                           aria-label="Disabled input example" disabled readonly>
                                </div>
                            </div>
                        <?php else: ?>
                            <div class="text-center alert alert-warning" role="alert">
                                <?php esc_html_e("Viewport not found", "bucky-seo"); ?>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>
                <div class="card">
                    <div class="container text-center">
                        <i class="fa-solid fa-mobile-screen-button fa-5x"></i>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title text-center">AMP mobile</h5>
                        <p>
                            <?php esc_html_e("Accelerated Mobile Pages (AMP) can significantly improve the loading speed of your website on mobile devices. Consider implementing AMP to enhance your mobile user experience.", "bucky-seo"); ?>
                        </p>
                        <?php
                        $count_amphtml_links = !empty($results['amphtml_links']) ? count($results['amphtml_links']) : 0;
                        ?>
                        <?php if ($count_amphtml_links > 0): ?>
                            <div class="text-center alert alert-success" role="alert">
                                <?php esc_html_e("AMP pages", "bucky-seo"); ?>
                                : <?php echo esc_html($count_amphtml_links); ?>
                            </div>
                        <?php else: ?>
                            <div class="text-center alert alert-warning" role="alert">
                                <?php esc_html_e("AMP pages not found", "bucky-seo"); ?>
                            </div>
                        <?php endif; ?>

                        <?php if ($count_amphtml_links > 0): ?>
                            <table class="table table-striped">
                                <thead>
                                <tr>
                                    <th scope="col">URL</th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php foreach ($results['amphtml_links'] as $amphtml_links): ?>
                                    <tr>
                                        <td><a href="<?php echo esc_url($amphtml_links); ?>"
                                               target="_blank"><?php echo esc_html($amphtml_links); ?></a></td>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                            </table>
                        <?php else: ?>
                            <p><?php esc_html_e("AMP not found", "bucky-seo"); ?></p>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>

        <div class="container breakhtml2pdf">
            <h1 class="display-5"><?php esc_html_e("Wordpress analysis", "bucky-seo"); ?></h1>
            <small><b><?php echo esc_html($generateapplied_text); ?></b>: <?php echo esc_html(get_site_url()); ?> |
                <b><?php echo esc_html($generatedby_text); ?></b>: <?php echo esc_html($seo_tool_name); ?></small>
            <span class="placeholder col-12 bg-success"></span>
            <div class="card-group">
                <div class="card">
                    <div class="container text-center">
                        <i class="fa-brands fa-expeditedssl fa-5x"></i>
                    </div>
                    <div class="card-body">
                        <p>
                            <?php esc_html_e("SSL is a security protocol that encrypts communication between browsers and websites.", "bucky-seo"); ?>
                        </p>
                        <h5 class="card-title text-center">HTTPS</h5>
                        <?php if (isset($results['is_https']) && $results['is_https'] === true): ?>
                            <div class="text-center alert alert-success" role="alert">
                                <?php esc_html_e("This site has SSL enabled and uses HTTPS", "bucky-seo"); ?>
                            </div>
                        <?php else: ?>
                            <div class="text-center alert alert-danger" role="alert">
                                <?php esc_html_e("This site lacks SSL encryption and HTTPS is not enabled. These technologies are crucial for securing communication between your website and users. Consider enabling them to protect user data and improve trust.", "bucky-seo"); ?>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>

                <div class="card">
                    <div class="container text-center">
                        <i class="fa-brands fa-wordpress fa-5x"></i>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title text-center"><?php esc_html_e("Wordpress version", "bucky-seo"); ?></h5>
                        <p>
                            <?php esc_html_e("Keeping WordPress updated is essential, just like any other software. This ensures you benefit from new features, improved performance, and the latest bug fixes.", "bucky-seo"); ?>
                        </p>
                        <?php if (isset($results['current_version'])): ?>
                            <div class="text-center alert alert-success" role="alert">
                                <p><?php esc_html_e("Actual version of Wordpress", "bucky-seo"); ?>
                                    : <?php echo esc_html($results['current_version']); ?></p>
                                <p><?php esc_html_e("Most recent version of Wordpress", "bucky-seo"); ?>
                                    : <?php echo esc_html($results['latest_version']); ?></p>
                            </div>
                            <?php if ($results['is_up_to_date']): ?>
                                <div class="text-center alert alert-success" role="alert">
                                    <?php esc_html_e("Your version is up to date", "bucky-seo"); ?>
                                </div>
                            <?php else: ?>
                                <div class="text-center alert alert-danger" role="alert">
                                    <?php esc_html_e("For optimal performance and security, consider updating to the latest version.", "bucky-seo"); ?>
                                </div>
                            <?php endif; ?>
                        <?php endif; ?>
                    </div>
                </div>


            </div>

            <div class="card-group">
                <div class="card">
                    <div class="container text-center">
                        <i class="fa-solid fa-file-arrow-up fa-5x"></i>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title text-center"><?php esc_html_e("Total installation size", "bucky-seo"); ?></h5>
                        <p>
                            <?php esc_html_e("Larger files take longer to load due to increased data transfer. Additionally, they consume more server storage space", "bucky-seo"); ?>
                        </p>
                        <?php if (isset($results['directory_size'])): ?>
                            <div>
                                <div class="text-center alert alert-warning" role="alert">
                                    <?php esc_html_e("Size installation", "bucky-seo"); ?>:
                                    <br><?php echo esc_html($results['directory_size']); ?>
                                </div>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>

                <div class="card">
                    <div class="container text-center">
                        <i class="fa-solid fa-folder-tree fa-5x"></i>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title text-center"><?php esc_html_e("Active theme", "bucky-seo"); ?></h5>
                        <p>
                            <?php esc_html_e("In terms of SEO, there's no single 'best' WordPress theme. However, a modern theme that follows accessibility best practices, SEO guidelines, and utilizes lightweight frameworks can significantly benefit your website's search ranking and user experience.", "bucky-seo"); ?>
                        </p>
                        <?php if (isset($results['active_theme'])): ?>
                            <?php $active_theme = wp_get_theme(); ?>
                            <?php if ($active_theme instanceof WP_Theme): ?>
                                <div>
                                    <div class="text-center alert alert-success" role="alert">
                                        <?php esc_html_e("Active theme", "bucky-seo"); ?>
                                        : <?php echo esc_html($active_theme->get('Name')); ?>
                                    </div>
                                </div>
                            <?php else: ?>
                                <div class="text-center alert alert-danger" role="alert">
                                    <?php esc_html_e("There is not active theme", "bucky-seo"); ?>
                                </div>
                            <?php endif; ?>
                        <?php endif; ?>
                    </div>
                </div>

            </div>

            <div class="card-group">
                <div class="card">
                    <div class="container text-center">
                        <i class="fa-solid fa-plug-circle-exclamation fa-5x"></i>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title text-center">Plugins</h5>
                        <p>
                            <?php esc_html_e("Inactive plugins, though seemingly harmless, are still executable files. This means they could be compromised during a hacking attempt, potentially allowing malware installation on your site. To minimize this risk, it's recommended to delete any inactive plugins you won't be using as a WordPress security best practice.", "bucky-seo"); ?>
                        </p>
                        <?php $count_inactive_plugins = count($results['inactive_plugins']);
                        $count_active_plugins = count($results['active_plugins']); ?>
                        <?php if ($count_active_plugins > 0): ?>
                            <div class="text-center alert alert-warning" role="alert">
                                <?php esc_html_e("Active plugins", "bucky-seo"); ?>
                                : <?php echo esc_html($count_active_plugins); ?>
                            </div>
                        <?php else: ?>
                            <div class="text-center alert alert-danger" role="alert">
                                <?php esc_html_e("Not active plugins", "bucky-seo"); ?>
                            </div>
                        <?php endif; ?>

                        <?php if ($count_inactive_plugins > 0): ?>
                            <div class="text-center alert alert-danger" role="alert">
                                <?php esc_html_e("Inactive plugins", "bucky-seo"); ?>
                                : <?php echo esc_html($count_inactive_plugins); ?>
                            </div>

                        <?php endif; ?>

                        <?php if ($count_inactive_plugins > 0): ?>
                            <div class="list-group">
                                <?php foreach ($results['inactive_plugins'] as $plugin_info): ?>
                                    <a class="list-group-item list-group-item-danger list-group-item-action"><?php echo esc_html($plugin_info['Name']); ?></a>
                                <?php endforeach; ?>
                            </div>
                        <?php else: ?>
                        <?php endif; ?>
                    </div>
                </div>

                <div class="card">
                    <div class="container text-center">
                        <i class="fa-solid fa-link fa-5x"></i>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title text-center"><?php esc_html_e("Permalinks", "bucky-seo"); ?></h5>
                        <p>
                            <?php esc_html_e("A well-designed URL structure plays a crucial role in SEO. It helps search engines understand the hierarchy and content of your website, potentially improving your search ranking.", "bucky-seo"); ?>
                        </p>
                        <?php if (isset($results['permalink_structure_active'])): ?>
                            <div class="permalink-structure-info">
                                <?php if ($results['permalink_structure_active']): ?>
                                    <div class="text-center alert alert-success" role="alert">
                                    <?php if (isset($results['permalink_structure_value'])): $permalink_structure = $results['permalink_structure_value'];
                                        switch ($permalink_structure) {
                                            case '/%year%/%monthnum%/%day%/%postname%/':
                                                echo esc_html_e("Day and name", "bucky-seo");
                                                break;
                                            case '/%postname%/':
                                                echo esc_html_e("Post name", "bucky-seo");
                                                break;
                                            case '/archivo/%post_id%':
                                                echo esc_html_e("Numeric", "bucky-seo");
                                                break;
                                            case '/%year%/%monthnum%/%postname%/':
                                                echo esc_html_e("Month and name", "bucky-seo");
                                                break;
                                            default:
                                                echo esc_html__("Custom structure", 'bucky-seo');
                                        } ?>
                                        </div>
                                    <?php else: ?>
                                        <div class="text-center alert alert-success" role="alert">
                                            <?php esc_html_e("Permalinks not defined", "bucky-seo"); ?>
                                        </div>
                                    <?php endif; ?>
                                <?php else: ?>
                                    <div class="text-center alert alert-success" role="alert">
                                        <?php esc_html_e("Permalinks not active", "bucky-seo"); ?>
                                    </div>
                                <?php endif; ?>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>


            </div>


        </div>


    </div>

</div>
